package com.environmental.dao;

import com.environmental.entity.EnvAllinfo;
import com.environmental.entity.EnvAllinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EnvAllinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table env_allinfo
     *
     * @mbggenerated
     */
    int countByExample(EnvAllinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table env_allinfo
     *
     * @mbggenerated
     */
    int deleteByExample(EnvAllinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table env_allinfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table env_allinfo
     *
     * @mbggenerated
     */
    int insert(EnvAllinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table env_allinfo
     *
     * @mbggenerated
     */
    int insertSelective(EnvAllinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table env_allinfo
     *
     * @mbggenerated
     */
    List<EnvAllinfo> selectByExample(EnvAllinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table env_allinfo
     *
     * @mbggenerated
     */
    EnvAllinfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table env_allinfo
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") EnvAllinfo record, @Param("example") EnvAllinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table env_allinfo
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") EnvAllinfo record, @Param("example") EnvAllinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table env_allinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EnvAllinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table env_allinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EnvAllinfo record);
}